version: 2
updates:
  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/" # root directory
    schedule:
      interval: "weekly" # could be daily, weekly, monthly
      day: "sunday" # only for weekly/monthly
      time: "12:55" # UTC time
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Optional: GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "ci"
